SPECTATORS_TEAM_ID = "team:spectators"

# Keep an attribute update within the update state for 15s
PARTIAL_GAME_STATE_TIME = 15


UNIT_DEFAULT_HEALTH_REGEN = 0
UNIT_DEFAULT_HEALTH_MAX = 100

UNIT_DEFAULT_COMBAT_RANGE = 1
UNIT_DEFAULT_COMBAT_ATTACK = 20
UNIT_DEFAULT_COMBAT_DEFENSE = 10
UNIT_DEFAULT_COMBAT_RELOAD = 0

UNIT_DEFAULT_MOVEMENT_RANGE = 2


